### ISSUE TITLE
Support using production docker image

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/mattermost-api#22]
At present, the testing process for this library assumes that the `mattermost-preview` image is appropriate for testing. While I think having a build against that image is very useful to find out about upcoming release incompatibility, it breaks our builds when it gets updated because we don't have a way of testing against the current release. So the task for this ticket is to figure out whether there exists a production docker image of mattermost that we can use for our testing when that's what we want, and then update the testing script to choose which image to use.

**Comment by dagit** [comment]
The last time I looked into it, it was the only docker image. I think 'preview' just means 'trial', but maybe they mean 'prerelease'.

**Comment by jtdaugherty** [comment]
So far I've found that you can build a local docker image for production use with the instructions at

https://docs.mattermost.com/install/prod-docker.html

but more work will be needed to get the test suite to work with it.

**Comment by jtdaugherty** [comment]
@jasonblais - can you comment on this? Our desire is to be able to run our test suite against a docker image for a specific version of MatterMost, but right now all we use is `mattermost-preview`. That worked for a while until that image got updated, and then our tests broke (around the time of the `3.7` releases).

So my question is: what's the best way to be sure that we're using the right version of MatterMost in our docker-based testing?

**Comment by aisamanra** [comment]
This is fixed by specifying a tag in the testing script, added in mattermost-api/1cf6330.
