### ISSUE TITLE
Make sure all endpoints use non-`Value` types

### ISSUE THREAD

**Issue by aisamanra** [matterhorn-chat/mattermost-api#24]
A few endpoints still return a raw `aeson` `Value` instead of a proper type. We should fix that.

**Comment by dagit** [comment]
Aside from a few uses of `HashMap` (which I'm okay with), I only see three offending functions:

- [ ] `mmGetConfig`
- [ ] `mmSaveConfig`
- [x] `mmExecute`

**Comment by jtdaugherty** [comment]
This ticket is now defunct due to using the APIv4 implementation.
