### ISSUE TITLE
avoid exposing JSON values to the user

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/mattermost-api#3]
At the moment many of the functions of the form `mmFoo` return something of the form `MM ([Header], Value)`. This exposes clients of the API to the fact that we use HTTP and JSON to communicate with the server. It would be better if we abstracted over these details.

We should make an effort to call `fromJSON` on the `Value` before returning it and the user shouldn't need the headers. It should be enough to `assert` that we got a positive response from the other end (`200` or similar). Any meaningful headers should be reinterpreted and returned as a flag of some sort.

There is at least one thing that will make it hard to hide all the `JSON` details: We don't know how to interpret all the fields of the `JSON` blobs that we get back from mattermost. This will take some experimentation and reading of the mattermost code to figure out. As a compromise we should make an effort to convert all the top level types that we return into our own types. If there are fields we don't currently understand, we can either leave those uninterpreted (as strings) or Aeson's `Value` type (but only as a last resort).

**Comment by dagit** [comment]
Most exposed API functions now return meaningful types instead of a raw `Data.Aeson.Value`.

**Comment by aisamanra** [comment]
As of right now, we don't have any exposed types that expose `Data.Aeson.Value` as a field, so I'm going to close this, and trust that we'll do it right going forward.
