### ISSUE TITLE
Add HTTP connection pooling

### ISSUE THREAD

**Issue by abhin4v** [matterhorn-chat/mattermost-api#43]
Currently, each HTTP request opens a new connection to the server. This causes a noticeable lag on slow internet connections.
A possible solution is to implement pooling for HTTP connections using a library like https://hackage.haskell.org/package/resource-pool.

**Comment by abhin4v** [comment]
FYI, I'm willing to implement this.

**Comment by abhin4v** [comment]
This issue should be closed now, right?

**Comment by jtdaugherty** [comment]
Yes - thanks!
