### ISSUE TITLE
Improve logging support

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/mattermost-api#6]
There are lots of times when it would be nice to increase logging in various ways. A common problem is having a json object not decode as expected or a field to be set in an unexpected way.

**Comment by aisamanra** [comment]
There's currently _some_ logging support: it's missing some important bits (especially errors!) but each `ConnectionData` value has an optional `Logger` field, which is a function that can be called with certain kinds of log events. Additionally, there are several different predefined `Logger` functions in `Network.Mattermost.Logging`, including some which take a filter to decide which messages to log. This can be useful if you're interested in a particular log message, or messages from a particular function, e.g.

``` .haskell
let myLogger l = mmLoggerDebugFilter $ \ l -> logFunction l == "mmPost"
let cd' = connectionData `withLogger` myLogger
```

will only log events that arise from the function `mmPost`.

I'm going to leave the issue open, but am leaving this comment to note that it's currently in progress.

**Comment by dagit** [comment]
Thanks for working on this!

BTW, it looks like you might have some uncommitted changes: https://travis-ci.org/dagit/mattermost-api/jobs/155790663

**Comment by aisamanra** [comment]
We now log websocket events, pings, pongs, &c. Accordingly, I think it's safe to close this issue—we just need to be sure to include logging in any new functions/endpoints we include.
